version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_USER=cong
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp